# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: #About\
    weight: 1
  - name: Biological Physics
    identifier: research
    weight: 10
  - name: Self-assembly of emerin nanodomains
    parent: research
    url: /research/self-assembly-of-emerin-nanodomains/
    weight: 10
  - name: Thermosensing through membrane mechanics
    parent: research
    url: /research/thermosensing-through-membrane-mechanics/
    weight: 20
  - name: Protein-induced bilayer deformations
    parent: research
    url: /research/protein-induced-bilayer-deformations/
    weight: 30
  - name: Microorganisms in quasi-2D membranes
    parent: research
    url: /research/microorganisms-in-quasi-2d-membranes/
    weight: 40
  - name: Publications
    url: '/publications/'
    weight: 30
  - name: CBS Poster 2022
    url: '/posters/qcb-2022/qcb-2022-poster.pdf'
    weight: 50
  - name: 'PDA Gallery'
    url: '/pda-gallery/'
    weight: 60
  - name: Contact
    url: '/contact/'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
